### ISSUE TITLE
Possibilité de développer une app iOS

### ISSUE THREAD

**Issue by petaire92** [insoumis-local/kitcampagne.fi#11]
Je suis developpeur iOS à la base, donc si une app iOS vous semble utile, n'hésitez pas…

**Comment by necropotame** [comment]
Pour le moment, on va le faire en responsive design je pense. Mais on garde ça dans un coin de la tête :)

**Comment by ryuran** [comment]
Je ne pense pas que ce soit utile sur ce projet. Pas d’intéret d’avoir ce kit dans sa poche tout le temps.
Peut-être qu'on a besoin d'app pour d'autre projet.

**Comment by ryuran** [comment]
Je ferme l'issue pour voir plus clair.
